## COMP3670/6670 Programming Assignment 1
---
### Pledge of Academic Integrity
I am committed to being a person of integrity.

I pledge, as a member of the Australian National University community,
to abide by and uphold the standards of academic integrity outlined in
the ANU statement on
[honesty and plagiarism](http://www.anu.edu.au/students/program-administration/assessments-exams/academic-honesty-plagiarism),
and I am aware of the relevant
[legislation](https://www.legislation.gov.au/Details/F2021L00997),
and understand the consequences of me breaching those rules. I confirm that I understand Assignment 1 of COMP 3670/6670 is not a group assignment and I am submitting work that is my own and I will disclose the assistance from any other agent (human or AI) in the production of the content included in the submission of this assignment.

**Signed**

**Enter Your Student ID:** u7283652

**Your Name:** Razeen Wasif

**Date:** Aug 20, 2024

---
### Instructions
**Deadline: 5pm, Aug 28, 2024.**

Late submissions will be permitted without penalty till 4:59pm Aug 29, 2024.

Late submissions beyond 4:59pm Aug 29, 2024 will encounter a 100\% penalty.

College-approved extenuating circumstances permit assessment extensions which need to be filed online [here](https://wattlecourses.anu.edu.au/mod/url/view.php?id=3227591) before the assignment deadline, 5pm, Aug 28, 2024. Approval of extension requests are governed by university policies and will take into account any submitted proof of extenuating circumstances.

**Submit:** Write your answers in this file, and submit a single Jupyter Notebook file (.ipynb) on Wattle. Rename this file with your student number as 'uXXXXXXX.ipynb'.


---
**Marking distribution for the assignment**

- Task1 = 10%
  - 1.1: 2.5%
  - 1.2: 2.5%
  - 1.3: 2.5%
  - 1.4: 2.5%
- Task2 = 50%
  - 2.1: 25%
  - 2.2: 10%
  - 2.3: 15% 
- Task3 = 40%
  - 3.1: 14%
  - 3.2: 10%
  - 3.3: 16%

The total marks percentage in this programming assignment will count towards a maximum of 10 points in the course. 

**Rubric**
This notebook includes some examples (tests) which you can use to test your function implementations. 

During grading, we will use a set of test cases (for e.g., inputs and matrices which will be different from the examples) to evaluate your functions. For each subtask, we will check the output from your functions for a set of test cases. 

If a subtask is worth X, there are Y test cases, and your code passes Z out of Y test cases, you get X*Z/Y credits for that subtask. We will use one test case in subtasks 1.1, 1.2, 1.3, 1.4, 2.1, 3.2, 3.3. There will be two test cases in subtasks 2.2, 3.1. Three test cases in 2.3.

There will be no partial credit if a test case does not pass, i.e., you will not receive any credit for the nature and content of your implementation beyond the evaluation of test cases according to the formula X*Z/Y described above. You will be penalized for using unapproved imports or if your code fails to run. 

Test cases will be published alongside the grades after the submission deadline.

## Task 0: Introduction
---

**NOTE:** *This part of the first assignment is by necessity somewhat tedious as its primary purpose is to introduce syntax, how to access and understand the Numpy documentation and some very basic concepts. If you are already familiar with Numpy, you can just read the **TASK** headings and complete the questions without worrying about all the additional information. This is designed for people who have never seen Numpy before, so it's a very easy 1st year style introduction to just introduce syntax.*

*As this is a third year subject, it is assumed you already know to to program well (but may be unfamiliar with Python and Numpy).*

---

Arguably the most fundamental tool needed to engage with machine learning in Python is Numpy *(np)*. To include Numpy in any project, simply type the following line at the top of your python file:

In [1]:
# numpy
import numpy as np

# !pip install sympy
import sympy as sp

# matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

A Jupyter Notebook is divided into cells, each of which works like a Python module or Latex file. When a cell is run, any cells that follow it will have access to its results. Running the above cell will give all following cells access to the Numpy library.

-----------

   **TASK 0.1:** To run the above cell, select it by clicking on it, hold **shift** and press **return**. If you have succeeded, then the cell will print "Done" just above.


-----------

Numpy is a library of common mathematical data structures and algorithms used in machine learning. For example:

- It allows you to declare vectors and matrices, with all the associated mathematical operations like matrix vector products, matrix addition / subtraction.
- It provides convenient, efficient implementations of algorithms to solve matrix equations, find the inverse of a matrix or perform Eigen decomposition. The implementation of these algorithms is compiled from C code, making Numpy much faster than programming these algorithms yourself in Python.

You'll need to know Numpy inside and out. We'll start by getting you familiar with the easy to access online documentation and performing a few basic operations.

Below I have declared the matrices: 

$$A = 
\begin{bmatrix}
2&3\\
0&1\\
\end{bmatrix}
\\
x = 
\begin{bmatrix}
1\\
3\\
\end{bmatrix}
$$. 

---
**TASK 0.2:** Run the cell below and observe what it prints.


---
(If it throws an error, you have the wrong version of python installed. This entire course will use Python 3, not Python 2)



In [2]:
A = np.array([[2, 3], [0, 1]])
x = np.array([[1], [3]])

#Matrix Multiplication Example
b = A @ x
print('\nMatrix Multiplication')
print(b)


Matrix Multiplication
[[11]
 [ 3]]


The above code illustrates how to perform matrix multiplication. Memorise it. Below are some other basic operations you'll likely need over the coming semester:

In [3]:
#Matrix Addition Example
b = A + x
print('\nMatrix Addition')
print(b)

#Elementwise Multiplication Example
b = A * x
print('\nElementwise Matrix Multiplication')
print(b)

#Extract a single element of a matrix:
print('\nSingle Element Extraction')
b = A[0, 0]
print(b)

#Extract an entire column of a matrix:
print('\nColumn Extraction')
b = A[:, 0]
print(b)

#Extract an entire row of a matrix:
print('\nRow Extraction')
b = A[0, :]
print(b)

#Transpose of a matrix:
print('\nTranspose')
A_Transpose = A.T
print(A_Transpose)


Matrix Addition
[[3 4]
 [3 4]]

Elementwise Matrix Multiplication
[[2 3]
 [0 3]]

Single Element Extraction
2

Column Extraction
[2 0]

Row Extraction
[2 3]

Transpose
[[2 0]
 [3 1]]


## Task1: Solving a system of linear equations
---

A vital part of linear algebra is to know how to solve a system of linear equations. For e.g. 

$$a_{11}x_1+a_{12}x_2 \dots a_{1d}x_d=b_1$$
$$a_{21}x_1+a_{22}x_2 \dots a_{2d}x_d=b_2$$
$$\vdots$$
$$a_{n1}x_1+a_{n2}x_2 \dots a_{nd}x_d=b_n$$

The above system of linear equations can also be written down in a compact matrix form as follows:

$$AX = B$$

where,
$$A = \begin{bmatrix}
a_{11} & \dots & a_{1d}\\
\vdots & \ddots & \vdots \\
a_{n1} & \dots & a_{nd}
\end{bmatrix}, \quad
B = \begin{bmatrix}
b_1 \\ \vdots \\ b_n
\end{bmatrix}, \quad
X = \begin{bmatrix}
x_1 \\ \vdots \\ x_d
\end{bmatrix}.
$$

---
**Task 1.1**: Use numpy's solve function to compute X

---
**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html

In [4]:
# define A,B
A = np.array([[10, 14, 4], [15, 2, 6], [7, 8, 18]])
B = np.array([[2], [1], [2]])

def solve_with_numpy(A,B):
    # TODO: solve the linear system
    return np.linalg.solve(A,B)

# show solution
X = solve_with_numpy(A,B)
print (X)

[[0.03185596]
 [0.10526316]
 [0.05193906]]


A more hands on way for solving for X, involves computing first computing the inverse of the matrix $A$

---
**Task 1.2**: Use numpy's inbuilt method for computing the inverse of the matrix $A$

---

**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html

In [5]:
A = np.array([[7, 1], [15, 4]])

def find_inverse(A):
    # TODO: find the inverse of the matrix A
    return np.linalg.inv(A)
    
A_inv = find_inverse(A)
print(A_inv)

[[ 0.30769231 -0.07692308]
 [-1.15384615  0.53846154]]


---
**Task 1.3**: Use the inverse of matrix $A$, to solve for $X$. **Note that you are only allowed to use the functions in 1.1 and 1.2. No other library functions are allowed**.

---

In [6]:
A = np.array([[5, 3], [2, 11]])
B = np.array([[16], [5]])

def solve_with_prev_tasks(A, B):
    # TODO: solve the linear system using functions you have written
    # A^-1 * B
    return np.linalg.inv(A) @ B

X = solve_with_prev_tasks(A, B)
print(X)

[[ 3.28571429]
 [-0.14285714]]


But what if $A$ is not a square matrix?

---
**Task 1.4**: Compute the Moore-Penrose pseudo inverse for matrix $A$ and **use it to solve for $x$**. **Note that, you must not directly use `np.linalg.pinv` for computing the pseudo-inverse**.

---

In [7]:
A = np.array([[15, 1], [5, 10], [8, 2], [11, 19]])
B = np.array([[18], [15], [2], [8]])

def pseudo_inverse(A):
    # TODO: find the pseudo inverse of a matrix
    return np.linalg.inv(A.T @ A) @ A.T

def solve_with_pseudo_inverse(A, B):
    A_pseudo = pseudo_inverse(A)
    # TODO: solve for x using pseudo inverse method.
    return A_pseudo @ B

X = solve_with_pseudo_inverse(A, B)
    
print(X)

[[0.97187421]
 [0.09046455]]


## Task 2: Solving a system of linear equations with Gaussian elimination

In the last task, we used numpy's inbulit functions to solve a system of linear equations. Lets do it without using these functions!

---
**Task 2.1**:  Complete the following gaussian elimnation function to compute the **reduced row-echelon form** of matrix $A$. You must implement the gaussian elimination algorithm yourself, not merely call someone else's library function. You **MUST NOT** copy codes from any source. Your function needs to work under **different shapes** of matrix. Negative zero is a result of the floating-point number standard. If you have some -0s instead of 0s, that should be fine.

---

In [8]:
def forward_elimination(res, rows, cols):
    """
    This function finds the maximum value of a column
    and makes it the pivot of the column through row swapping
    as well as transforms matrix into upper-triangle form

    Parameters:
    - res: A matrix
    - rows: the number of rows in res
    - cols: the number of cols in res
    """
    row, col = 0, 0
    while row < rows and col < cols:
        # Loop through entire matrix and swap rows
        # Find the maximum value in the current column.
        # This will be the pivot of the column.
        pivot_col = np.argmax(np.abs(res[row:, col])) + row
        
        # If the maximum value is zero (column of zeros), 
        # continue to the next column
        if abs(res[pivot_col, col]) < 1e-10:
            col += 1
            continue
        # swap current row with row with max value in pivot
        if pivot_col != row:
            res[[row, pivot_col]] = res[[pivot_col, row]]
            
        for r in range(row + 1, rows):
            factor = res[r, col] / res[row, col]
            res[r, col:] -= factor * res[row, col:]
        # Increment the rows and columns to move on
        row += 1
        col += 1
    return res

def backward_elimination(res, rows, cols):
    """
    This function tranforms a upper-triangle matrix to rref.
    Parameters:
    - res: the upper-triangle form matrix
    - rows: the number of rows in res
    - cols: the number of cols in res
    """
    # Find factor
    for row in range(min(rows, cols)-1, -1, -1):
        for next_row in range(row-1, -1, -1):
            if res[row, row] != 0:
                factor = res[next_row, row] / res[row, row]
                # make all values above pivot zero
                res[next_row, row:] -= factor * res[row, row:]
    return res
    
def make_pivots_one(res, rows, cols):
    """
    This function normalizes the pivots of a reduced matrix to 1

    Parameters:
    - res: the reduced matrix
    - rows: the number of rows in res
    - cols: the number of cols in res
    """
    # make diagonals one
    for row in range(min(rows, cols)):
        pivot = res[row, row]
        if pivot != 0:
            res[row] /= pivot
    return res

def gaussian_elim(X):
    '''
    This function uses the Gaussian elimination algorithm to reduce
    a matrix to its row reduced echelon form
    
    Parameters:
    - X: The matrix to row-reduce
    
    Returns:
    - A matrix in row-reduced echelon form
    '''
    rows, cols = X.shape
    res = np.array(X, dtype=np.float64)
    # TODO: implement Gaussian Elimination on any matrix.
    # print(f"The matrix to row-reduce is:\n {X}")
    forward_elimination(res, rows, cols)
    res[abs(res) < 1e-10] = 0
    # print(f"The matrix after forward elim is:\n {res}")
    backward_elimination(res, rows, cols)
    # res[abs(res) < 1e-10] = 0
    # print(f"The matrix after backward elim is:\n {res}")
    make_pivots_one(res, rows, cols)
    # res[abs(res) < 1e-10] = 0
    # print(f"The matrix after normalizing is:\n {res}")
    # print(f"the row reduced matrix using sympy is:\n {sp.Matrix(X).rref()}")
    # print(f"the row reduced matrix using gauss elim is:\n {res}\n")
    # Do not change the following line
    res[abs(res) < 1e-10] = 0
    return res

In [9]:
C = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
print(gaussian_elim(C))

[[ 1.  0. -1.]
 [ 0.  1.  2.]
 [ 0.  0.  0.]]


In [10]:
A = np.array([[1,8,9],[3,2,6], [7,4,5]])
print(gaussian_elim(A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
A = np.array([[18, 18, 14, 15, 14, 19,  8,  7,  2, 11],
               [ 3,  7,  8,  8,  2,  2,  8, 17,  6,  8],
               [ 2,  8,  6,  4, 11, 10, 15, 11, 12,  3],
               [ 9,  4, 17,  6,  6, 12, 13,  0, 12,  2],
               [ 0,  3, 18,  0, 13,  6,  8, 13, 16, 15],
               [15, 16, 13,  9,  4, 17, 11,  0,  5, 18],
               [10,  4,  6, 12,  6, 18, 17,  7,  5,  6],
               [ 3, 12,  2,  4, 16,  1, 17,  8, 10,  2],
               [ 7,  8, 11,  4, 12, 14, 18, 14,  9, 16],
               [18, 13,  3, 19, 16,  9,  6,  8,  2, 15]])

print(gaussian_elim(A))

# The result should be an identity matrix

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [12]:
B = np.array([[ 5,  3, 14,  1,  2, 15,  1, 11],
               [ 3, 13,  5, 18, 16, 18, 12,  4],
               [ 1,  9, 12, 15, 15,  0,  7,  0],
               [18, 17,  5,  0, 11,  4, 17,  9]])

print(gaussian_elim(B))
# The result should look like
# [[  1.           0.           0.           0.          -2.77442593 20.86492571  -0.07248987   7.64520486]
#  [  0.           1.           0.           0.           3.44146781 -21.02183701   1.11661414  -7.36402521]
#  [  0.           0.           1.           0.           0.48694282 -2.83948672  -0.13552454  -0.68505178]
#  [  0.           0.           0.           1.          -1.26947321 13.49369653  -0.09004953   4.45677623]]

[[  1.           0.           0.           0.          -2.77442593
   20.86492571  -0.07248987   7.64520486]
 [  0.           1.           0.           0.           3.44146781
  -21.02183701   1.11661414  -7.36402521]
 [  0.           0.           1.           0.           0.48694282
   -2.83948672  -0.13552454  -0.68505178]
 [  0.           0.           0.           1.          -1.26947321
   13.49369653  -0.09004953   4.45677623]]


In [13]:
C = np.array([[ 3, 12, 17],
               [14, 19,  8],
               [ 1, 12,  7],
               [10, 17, 11],
               [ 6,  0, 12],
               [16,  3, 15],
               [16, 19, 18]])

print(gaussian_elim(C))
# The result should look like
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]
#  [0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
C = np.array([[-0.62654533, -0.31002168, -0.34649087, -0.42208842],
 [ 2.61837699,  0.92174822, -0.26810391, -2.40159578],
 [ 0.41028528, -0.42190761,  0.46844453, -0.91905418],
 [ 0.41028528, -0.42190761,  0.46844453, -0.91905418]])
print(gaussian_elim(C))

[[ 1.          0.          0.         -1.65307985]
 [ 0.          1.          0.          2.62974947]
 [ 0.          0.          1.          1.85441692]
 [ 0.          0.          0.          0.        ]]


In [15]:
C = np.array([[-0.80226897,  1.29289075,  0.97913426, -2.18898515],
 [ 1.63014815,  0.79302078,  0.18669054,  0.15381826],
 [-0.23982889, -0.00487591, -0.30339143, -1.02539355],
 [-0.23982889, -0.00487591, -0.30339143, -1.02539355]])
print(gaussian_elim(C))

[[ 1.          0.          0.          1.18974509]
 [ 0.          1.          0.         -2.83667863]
 [ 0.          0.          1.          2.48487472]
 [ 0.          0.          0.          0.        ]]


Make sure you pass the following test. Note that, passing the test set does not guarantee you with full mark. We will use different cases when testing your implementation.

In [16]:
# test your gaussian_elim function
def test_gaussian_elim():
    for i in range(100):
        m, n = np.random.randint(low=5, high=10, size=2)
        a = np.random.randn(m, n)
        sol1 = gaussian_elim(a)
        sol2 = np.array(sp.Matrix(a).rref()[0])
        if np.sum((sol1 - sol2) ** 2) > 1e-6:
            print(a, "\n")
            print(gaussian_elim(a), "\n")
            print(np.array(sp.Matrix(a).rref()[0]), "\n")
            return False
    test_cases = [np.array([[2, 0, 1, 1],
                            [2, 0, 1, 1],
                            [0, 0, 0, 0],
                            [1, 1, 1, 0]], dtype=np.float64),
                  np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]], dtype=np.float64),
                  ]
    for test in test_cases:
        sol1 = gaussian_elim(test)
        sol2 = np.array(sp.Matrix(test).rref()[0])
        if np.sum((sol1 - sol2) ** 2) > 1e-6:
            print(test, "\n")
            print(gaussian_elim(test), "\n")
            print(np.array(sp.Matrix(test).rref()[0]), "\n")
            return False
    return True
test_gaussian_elim()

True

---
**Task 2.2**: A system of linear equations is called homogeneous if the right hand side is the zero vector. Sometimes there will be only trivial solution, namely the zero vector. An example of this matrix is:
$$2x_1+4x_2 =0$$
$$2x_1+5x_2 =0$$
Sometimes there will be non-trivial solutions, e.g.,
$$2x_1+4x_2 =0$$
$$1x_1+2x_2 =0$$
The solution can be $x_1 =-2$, $x_2 =1$.
 
$A=\big(\begin{smallmatrix}
  2 & 4\\
  1 & 2
\end{smallmatrix}\big)$ is called coefficient matrix.
Your task is solving a homogeneous system of linear equations based on its reduced row-echelon form, i.e., the output of your *gaussian_elim* function in Task 2.1. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1. Your function needs to work under **different shapes** of $A$. 

The *solve_homogeneous* function should be according to the following specifications:
* Take as input the coefficient matrix $A$. 
* Return:
    - 0 if it only has trivial solution. Type: int.
    - otherwise, return any two different non-trivial solutions. Type: tuple((np.ndarray, Type: np.ndarray)).  Note that the dimensions of the np.ndarray should be 1, i.e., using one pair of square brackets. See demo outputs below.

In [17]:
def find_pivots_and_free_vars(rref_A, rows, cols):
    """
    This function identifies the pivots columns and free variables
    
    Parameters
    - rref_A: rref matrix [A|0 or b]
    - rows: number of rows in rref_A
    - cols: number of cols in rref_A

    Returns:
    - pivot_columns: list of pivot columns
    - free_vars: list of free variables
    """
    # Identify pivot columns
    pivot_columns = [] # indexes of columns that are pivots
    for i, row in enumerate(rref_A):
        for col, element in enumerate(row[:-1]):
            if abs(element - 1) < 1e-10:
                pivot_columns.append(col)
                break
    # print(f"Identified pivot columns: {pivot_columns}")
    # Identify free variables (columns that do not have leading ones
    # (pivots))
    free_vars = [i for i in range(cols) if i not in pivot_columns]
    # print(f"The free variables are:\n {free_vars}")
    return pivot_columns, free_vars

def linalg_solve(rref_A, rows, cols):
    """
    This function solves systems of linear equations

    Parameters
    - rref_A: rref matrix [A|0 or b]
    - rows: number of rows in rref_A
    - cols: number of cols in rref_A
    Returns:
    - res: solved linear system
    """
    pivot_cols, free_vars = find_pivots_and_free_vars(rref_A, rows, cols)

    basis_null_space = np.array([])
    # for each free var (non pivot col), form a basis vector
    for free_var in free_vars:
        basis_vector = np.zeros(cols) # fill with zeros
        basis_vector[free_var] = 1 # set free var to 1 to solve basic variables

        # Loop through to populate the entries using the 
        # free var and get the vector in the null space.
        for row, pivot in enumerate(pivot_cols):
            basis_vector[pivot] = -rref_A[row][free_var]
        null_space = np.append(basis_null_space, [round(i, 8) for i in basis_vector])
                
    # Compute for [A|0]
    if np.all(rref_A[:, -1] == 0):
        return (np.array(null_space))
    # Compute for [A|b]
    else:
        # Compute particular solution
        particular = np.zeros(cols - 1)
        for row, pivot in enumerate(pivot_cols):
            particular[pivot] = rref_A[row, -1]
        return np.array(particular), np.array(null_space)

def solve_homogeneous(A):
    """
    This function uses gaussian elimination to solve a homogenous
    system of linear equations (Ax=0).
    
    Parameters:
    - A: The coefficient matrix
    
    Returns:
    - 0: if A only has the trivial solution
    - tuple: two different non-trivial solutions
    """
    # YOUR CODE HERE
    rows, cols = A.shape
    # define the zero vector
    zero_vector = np.zeros((rows, 1))
    # Row-reduce the augmented matrix
    augmented_A = np.hstack((A, zero_vector))
    rref_A = gaussian_elim(augmented_A)
    #print(f"The matrix is:\n {A}")
    #print(f"The row-reduced form of the matrix is:\n {rref_A}")

    # find the rank of A
    rank = 0
    for row in rref_A:
        if all(element == 0 for element in row[:-1]):
            continue
        else:
            rank += 1
    # If rank = number of columns then trivial solution
    if rank == cols:
        return 0
    elif rank < cols:
        # return the non-trivial solution
        sol = linalg_solve(rref_A, rows, cols)
        return (sol, list(map(lambda x: x * 2, sol)))

In [18]:
A = np.array([[1,8,9],[3,2,6],[7,4,5], [12,4,16]])
print(solve_homogeneous(A))

0


In [19]:
A = np.array([[ 6,  9,  1,  7],
               [17,  1,  3, 17],
               [ 8,  4,  9, 13],
               [18,  4, 18, 18]])
print(solve_homogeneous(A))
# The result should look like
# 0

0


In [20]:
B = np.array([[ 6,  8,  6, 15, 12],
           [17,  8,  8, 12,  2],
           [18, 15, 15,  7,  2],
           [ 7,  6, 10,  3, 18],
           [14,  4,  4,  2, 16]])
print(solve_homogeneous(B))
# The result should look like
# 0

0


In [21]:
C = np.array([[ 8, 18, 18],
               [14, 19, 15],
               [4,  9,  9]])

print(solve_homogeneous(C))
# The result should look like
# (array([ 0.72, -1.32,  1.  ]), array([ 1.44, -2.64,  2.  ]))
# Note they are not unique

(array([ 0.72, -1.32,  1.  ]), [1.44, -2.64, 2.0])


In [22]:
D = np.array([[10,  3,  2,  8],
           [16,  5,  8,  5],
           [ 0,  0, 13, 16]])

print(solve_homogeneous(D))
#The result should look like
# ((array([-21.11538462,  68.53846154,  -1.23076923,   1.        ]), 
# array([-42.23076923, 137.07692308,  -2.46153846,   2.        ]))
# Note they are not unique

(array([-21.11538462,  68.53846154,  -1.23076923,   1.        ]), [-42.23076924, 137.07692308, -2.46153846, 2.0])


In [23]:
E = np.array([[ 2, 12,  2],
           [12,  8,  7],
           [14,  5, 17],
           [ 8, 10,  5]])

print(solve_homogeneous(E))
# The result should look like
# 0

0


Make sure you pass the following test. Note that, passing the test set does not guarantee you with full mark. We will use different cases when testing your implementation.

In [24]:
def test_homogeneous_trivial():
    # test A with m>n and m=n but no dependent rows in it
    for i in range(1000):
        m = np.random.randint(low=4, high=6)
        n = np.random.randint(low=2, high=5)
        a = np.random.randn(m, n)
        res = solve_homogeneous(a)
        if res != 0:
            print(a, '\n')
            print(f' solution should be 0 but got {res}')
            return False
    # test A with m>n and there are dependent rows in it
    test_list = [
        np.array([[1, 2], [3, 4], [2, 4]]),
        np.array([[1, 2, 3], [2, 4, 6], [3, 4, 5], [4, 7, 9]]),
    ]
    for case in test_list:
        res = solve_homogeneous(case)
        if res != 0:
            print(a, '\n')
            print(f' solution should be 0 but got {res}')
            return False
    return True

def test_homogeneous_nontrivial():
    import random
    # test A with m=n and m<n
    for i in range(1000):
        m = np.random.randint(low=2, high=5)
        n = np.random.randint(low=4, high=6)
        a = np.random.randn(m, n)
        a_ = a.copy()
        # create matrices whose rows or columns are dependent
        dpdt = random.sample(range(0, m), np.random.randint(low=2, high=m + 1))
        duplicate = a[dpdt[0]]
        for row in dpdt:
            a[row] = duplicate
        x1 = np.expand_dims(solve_homogeneous(a)[0], axis=1)
        x2 = np.expand_dims(solve_homogeneous(a)[1], axis=1)
        if abs(np.sum(a @ x1)) > 1e-6 or abs(np.sum(a @ x2)) > 1e-6 or (x1==x2).all():
            print(a_, '\n')
            print('the solutions are not correct')
            return False
    # test A with m>n
    test_list = [
        np.array([[1, 2], [1, 2], [2, 4]]),
        np.array([[1, 2, 3], [3, 6, 9], [1, 2, 3], [4, 7, 9]]),
        np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    ]
    for case in test_list:
        x1 = np.expand_dims(solve_homogeneous(case)[0], axis=1)
        x2 = np.expand_dims(solve_homogeneous(case)[1], axis=1)
        if abs(np.sum(case @ x1)) > 1e-6 or abs(np.sum(case @ x2)) > 1e-6 or (x1==x2).all():
            print(a_, '\n')
            print('the solutions are not correct')
            return False
    return True

print(test_homogeneous_trivial())
print(test_homogeneous_nontrivial())

True
True


---
**Task 2.3**: A system of linear equations is called non-homogeneous if the right hand side is not the zero vector. A non-homogeneous system of linear equations has
* no solution, or
* a unique solution, or
* infinite number of solutions

Similar to Task 2.2, your task is solving a non-homogeneous system of linear equations. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1, however, you are allowed to use the functions you defined in Task 2.2. Your function needs to work under **different shapes** of augmented matrix $[A|b]$. 

The *solve_nonhomogeneous* function should be according to following specifications:
* Take as input the augmented matrix $[A|b]$. 
* Return:
    - None if it has no solution at all. Type: None.
    - the single solution if it only has one solution. Type: np.ndarray.
    - otherwise, return any two different solutions if it has more than one solutions. Type: tuple((np.ndarray, Type: np.ndarray)).
*  Note that the dimensions of the np.ndarray should be 1, especially, one pair of square brackets. See demo outputs below.    

In [25]:
def rank(A):
    # TODO: get rank of A
    rows, cols = A.shape
    rref_A = gaussian_elim(A)
    # print(rref_A)
    # rank is number of non-zero rows after rref, so loop through rows
    # to see how many rows are non-zero
    # set defualt rank to 0
    rank = 0
    for row in rref_A:
        if all(element == 0 for element in row):
            continue
        else:
            rank += 1
    return rank

In [26]:
def solve_nonhomogeneous(A_aug):
    """
    This function solves the non-homogenous system of linear 
    equations Ax = b

    Parameters:
    - A_aug: augmented matrix [A|b]

    Returns:
    - None: if there are no solutions
    - rtn: np array of single solution
    - (rtn, rtn): tuple of solutions if there are more than one
    """
    # TODO: solve for x for non homogeneous system
    rows, cols = A_aug.shape
    # First need to row-reduce the augmented matrix in question
    rref_A = gaussian_elim(A_aug)
    # print(f"The original matrix is:\n {A_aug}")
    # print(f"The row-reduced form of the matrix is:\n {rref_A}")
    # For system to have no solution, rk(A) != rk([A\b])
    rank_A, rank_A_aug = 0, 0
    for row in rref_A:
        if all(element == 0 for element in row):
            rank_A_aug += 1
        if all(element == 0 for element in row[:-1]):
            rank_A += 1
    if rank_A != rank_A_aug:
        # system has no solution
        return None
        
    particular, null_space_1 = linalg_solve(rref_A, rows, cols)
    # If A has full rank and sqaure
    if rank(rref_A[:, :-1]) == A_aug[:, :-1].shape[1] and A_aug[:, :-1].shape[0] == A_aug[:, :-1].shape[1]:
        # System has unique solution
        # print("Unique solution:")
        return particular
    else:
        # System has multiple solutions
        homogeneous_solutions = solve_homogeneous(A_aug[:, :-1]) 
        rtn = ()
        for arr in (particular + homogeneous_solutions):
            rtn += (arr,)
        # print(f"the tuple is:\n {rtn}")
        return rtn

In [27]:
A = np.array([[ 1.49824067, -0.23835097,  0.93452348, -0.18183278,  1.59803508],
 [ 0.155208,    0.81201992 ,-0.71963855, -0.07130462,  2.34524338],
 [-0.73123568,  0.50770485, -0.10868031 , 1.26382884,  0.808088  ],
 [ 0.155208,    0.81201992 ,-0.71963855 ,-0.07130462 , 2.34524338]])
print(solve_nonhomogeneous(A))

(array([ 2.01783315,  1.82334044, -0.86540026,  1.        ]), array([ 2.9198053 ,  0.28103249, -2.51024836,  2.        ]))


In [28]:
A = np.array([[ 9,  5, 14,  3],
           [ 9,  1, 11,  0],
           [ 0,  4,  3,  2]])

print(solve_nonhomogeneous(A))
# The result should look like
# None

None


In [29]:
B = np.array([[ 9, 19,  2, 18],
           [ 5,  7,  3, 14],
           [14,  6,  1,  9]])

print(solve_nonhomogeneous(B))
# The result should look like
# [0.19444444 0.52777778 3.11111111]

[0.19444444 0.52777778 3.11111111]


In [30]:
C = np.array([[14, 14,  0, 18,  2, 11],
           [12, 12,  5,  1, 19, 13],
           [ 9,  3,  7,  1,  2, 11],
           [18, 10,  6, 12,  8, 16]])

print(solve_nonhomogeneous(C))
# The result should look like
# (array([-2.99214286,  0.35642857,  4.61571429,  2.55      ,  1.        ]), 
# array([-6.15785714,  0.29357143,  8.08428571,  4.95      ,  2.        ]))
# The results are not unique

(array([-2.99214286,  0.35642857,  4.61571429,  2.55      ,  1.        ]), array([-6.15785715,  0.29357143,  8.08428572,  4.95      ,  2.        ]))


In [31]:
C = np.array([[14, 14,  0, 18,  2],
              [12, 12,  5,  1, 19],
              [ 9,  3,  7,  1,  2],
              [18, 10,  6, 12,  8]])

print(solve_homogeneous(C))

b1 = np.array([0.17357143, 0.41928571, 1.14714286, 0.15      , 0.  ])
b2 = np.array([-2.99214286,  0.35642857,  4.61571429,  2.55      ,  1.])
xn = np.array([-3.16571429, -0.06285714,  3.46857143,  2.4       ,  1.        ])

print(C @ b1)
print(C @ b2)
print(C @ xn)
print(b1 + xn)

(array([-3.16571429, -0.06285714,  3.46857143,  2.4       ,  1.        ]), [-6.33142858, -0.12571428, 6.93714286, 4.8, 2.0])
[10.99999996 12.99999998 11.00000002 16.        ]
[10.99999994 12.99999997 11.         15.99999996]
[-2.00000017e-08 -1.00000008e-08 -2.00000017e-08 -4.00000033e-08]
[-2.99214286  0.35642857  4.61571429  2.55        1.        ]


Make sure you pass the following test. Note that, passing the test set does not guarantee you with full mark. We will use different cases when testing your implementation.

In [32]:
def test_nonhomogeneous_no_solution():
    import random
    for i in range(1000):
        m = np.random.randint(low=3, high=6)
        n = np.random.randint(low=3, high=6)
        a = np.random.randn(m, n)
        a_ = a.copy()
        # create matrices whose rows conflict
        cflt = random.sample(range(0, m), np.random.randint(low=2, high=m + 1))
        duplicate = a[cflt[0]]
        for row in cflt:
            a[row] = duplicate
            a[row][-1] = np.random.normal(loc=a[row][-1])
        if solve_nonhomogeneous(a):
            print(a_, '\n')
            print(f'the solution should be None, but got {solve_nonhomogeneous(a)}')
            return False
    return True

def test_nonhomogeneous_single_solution():
    # test square A
    for i in range(1000):
        m = np.random.randint(low=3, high=6)
        n = m + 1
        a = np.random.randn(m, n)
        x = np.expand_dims(solve_nonhomogeneous(a), axis=1)
        if abs(np.sum(a[:, :-1] @ x) - np.sum(a[:, -1])) > 1e-6:
            print(a, '\n')
            print('the solution is not correct')
            return False
    test_list = [
        np.array([[1, 1, 1], [1, 3, 3], [2, 2, 2]]),
        np.array([[1, 2, 3, 2], [2, 4, 6, 4], [3, 6, 9, 6], [4, 7, 9, 10], [1, 2, 4, 7]]),
    ]
    # test A with m>n
    for case in test_list:
        x = np.expand_dims(solve_nonhomogeneous(case), axis=1)
        if abs(np.sum(case[:, :-1] @ x) - np.sum(case[:, -1])) > 1e-6:
            print(a, '\n')
            print('the solution is not correct')
            return False
    return True

def test_nonhomogeneous_infinite_solution():
    import random
    for i in range(1000):
        # test A with m=n and m<n whose rows are dependent
        m = np.random.randint(low=2, high=5)
        n = m + np.random.randint(low=1, high=4)
        a = np.random.randn(m, n)
        a_ = a.copy()
        # create matrices whose rows or columns are dependent
        dpdt = random.sample(range(0, m), np.random.randint(low=2, high=m + 1))
        duplicate = a[dpdt[0]]
        for row in dpdt:
            a[row] = duplicate
        x1 = np.expand_dims(solve_nonhomogeneous(a)[0], axis=1)
        x2 = np.expand_dims(solve_nonhomogeneous(a)[1], axis=1)
        if abs(np.sum(a[:, :-1] @ x1) - np.sum(a[:, -1])) > 1e-6 or abs(
                np.sum(a[:, :-1] @ x2) - np.sum(a[:, -1])) > 1e-6 or (x1==x2).all():
            print(a_, '\n')
            print('the solutions are not correct')
            return False
        # test A with m<n whose rows are not dependent
        if n > m + 1:
            x1 = np.expand_dims(solve_nonhomogeneous(a_)[0], axis=1)
            x2 = np.expand_dims(solve_nonhomogeneous(a_)[1], axis=1)
            if abs(np.sum(a[:, :-1] @ x1) - np.sum(a[:, -1])) > 1e-6 or abs(
                    np.sum(a[:, :-1] @ x2) - np.sum(a[:, -1])) > 1e-6 or (x1==x2).all():
                print(a_, '\n')
                print('the solutions are not correct')
                return False
    # test A with m>n whose rows are dependent
    test_list = [
        np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]]),
        np.array([[1, 2, 3, 4], [2, 4, 6, 8], [1, 4, 7, 9], [1, 2, 3, 4], [2, 4, 6, 8]]),
    ]
    for case in test_list:
        x1 = np.expand_dims(solve_nonhomogeneous(case)[0], axis=1)
        x2 = np.expand_dims(solve_nonhomogeneous(case)[1], axis=1)
        if abs(np.sum(case[:, :-1] @ x1) - np.sum(case[:, -1])) > 1e-6 or abs(
                np.sum(case[:, :-1] @ x2) - np.sum(case[:, -1])) > 1e-6 or (x1==x2).all():
            print(case, '\n')
            print('the solutions are not correct')
            return False
    return True

print(test_nonhomogeneous_no_solution())
print(test_nonhomogeneous_single_solution())
print(test_nonhomogeneous_infinite_solution())

True
True
True


## Task 3: Rank, Basis and Span

Given a matrix $X$, would it be possible for you to programmably determine its rank, null space and column space? In this question, you are tasked at **1) finding the rank and the dimension of the null space $X$, 2) finding the basis that spans the column space of $X$, and 3) finding the basis that spans the null space of $X$.**

---
**Task 3.1**: Implement two functions `rank`, `dim_null`.

`rank`: takes arbitrary matrix $X$ as input, output its rank.

`dim_null`: takes arbitrary matrix $X$ as input, output the dimension of its null space

**Note: If you didn't get Gaussian Elimination in task2, you may use the library function `sp.Matrix(X).rref()` to get the reduced row echelon form of $X$. But, you must not use other library functions that can solve questions directly.**

In [33]:
def rank(A):
    # TODO: get rank of A
    rows, cols = A.shape
    rref_A = gaussian_elim(A)
    # print(rref_A)
    # rank is number of non-zero rows after rref, so loop through rows
    # to see how many rows are non-zero
    # set defualt rank to 0
    rank = 0
    for row in rref_A:
        if all(element == 0 for element in row):
            continue
        else:
            rank += 1
    return rank
    
def dim_null(A):
    # TODO: get dimension of the null space of A
    rows, cols = A.shape
    rref_A = gaussian_elim(A)
    # the nullity is the number of free variables after rref, so 
    # identify columns with pivots (leading 1)
    pivot_columns = []
    
    for row in rref_A:
        for col, element in enumerate(row):
            if element == 1:
                pivot_columns.append(col)
                break
    # n - len
    return cols - len(pivot_columns)

In [34]:
A = np.array([[0, 0, 0], 
              [0, 0, 0], 
              [0, 0, 0]])

print(rank(A))
print(dim_null(A))

# you should get
# 0
# 3

0
3


In [35]:
B = np.array([[16,  8, 12,  8,  5],
               [ 0,  7,  9, 14,  2],
               [14, 12, 13, 15, 14],
               [13, 18, 16, 19, 12]])

print(rank(B))
print(dim_null(B))

# you should get
# 4
# 1

4
1


In [36]:
C = np.array([[ 1,  8,  4],
               [ 0,  0, 11],
               [15,  2, 11],
               [12,  0,  3]])

print(rank(C))
print(dim_null(C))

# you should get
# 3
# 0

3
0


Make sure you pass the following test. Here we only provide the test for the rank.

In [37]:
def test_rank():
    for _ in range(1000):
        rnd_h = np.random.randint(1, 10)
        rnd_w = np.random.randint(1, 10)
        rnd_mat = np.random.choice(100, [rnd_h, rnd_w], replace=True).astype(np.float64)
        if rank(rnd_mat) != np.linalg.matrix_rank(rnd_mat):
            return False
    return True
test_rank()

True



---
**Task 3.2**: Implement `basis_col`.

`basis_col`: takes arbitrary matrix $X$ as input, output a basis that spans the column space of $X$. The basis should be a numpy array or a list, containing several numpy array vectors. 

---

In [38]:
def basis_col(A):
    # TODO: get a basis for the column space.
    rows, cols = A.shape
    rref_A = gaussian_elim(A)
    
    # identify columns with pivots (leading 1)
    pivot_columns = []
    
    for row in rref_A:
        for col, element in enumerate(row):
            if element == 1:
                pivot_columns.append(col)
                break
    # The basis that spans the col space are the columns that
    # contain a pivot
    # Need to output the columns from pivot columns (has col idx)
    if pivot_columns == []:
        return np.zeros((rows,1))
    else:
        return A[:, pivot_columns] 

In [39]:
A = np.array([[0, 0, 0], 
              [0, 0, 0], 
              [0, 0, 0]])

print(basis_col(A))

# should return 
# array([[0], [0], [0]])

[[0.]
 [0.]
 [0.]]


In [40]:
B = np.array([[13, 11,  6,  9,  6],
            [ 0, 12, 16, 11, 14],
            [ 5, 15,  8,  3,  0],
            [16,  3,  1, 14,  5]])

print(basis_col(B))

# should return something like
# array([[13, 11, 6, 9], [0, 12, 16, 11], [5, 15, 8, 3], [16, 3, 1, 14]])
# the solution is not unique

[[13 11  6  9]
 [ 0 12 16 11]
 [ 5 15  8  3]
 [16  3  1 14]]


In [41]:
C = np.array([[1, 1], 
              [1, 1], 
              [1, 1]])

print(basis_col(C))
# should return something like
# array([[1], [1], [1]])
# the solution is not unique

[[1]
 [1]
 [1]]


We will use more test cases when testing your implementation.

---
**Task 3.3**: Implement `basis_null`.

`basis_null`: takes arbitrary matrix $X$ as input, output a basis that spans the null space of $X$. The basis should be a numpy array or a list, containing several numpy array vectors.

---

In [42]:
def basis_null(A):
    # TODO: get a basis for the null space.
    rows, cols = A.shape
    rref_A = gaussian_elim(A)
    
    # Identify pivot columns
    pivot_columns = [] # indexes of columns that are pivots
    for row in rref_A:
        for col, element in enumerate(row):
            if element == 1:
                pivot_columns.append(col)
                break

    # Identify free variables (columns that do not have leading ones
    # (pivots))
    free_vars = [i for i in range(cols) if i not in pivot_columns]
    
    basis_null_space = []
    # for each free var (non pivot col), form a basis vector
    for free_var in free_vars:
        basis_vector = np.zeros(cols) # fill with zeros
        basis_vector[free_var] = 1 # set free var to 1 to solve basic variables
    
        # Loop through to populate the entries using the 
        # free var and get the vector in the null space.
        for row, pivot in enumerate(pivot_columns):
            basis_vector[pivot] = -rref_A[row][free_var]

        basis_null_space.append([round(i, 6) for i in basis_vector])
    
    if basis_null_space == []:
        return np.zeros((rows,1))
    else:
        return np.array(basis_null_space).T

In [43]:
A = np.array([[0, 0, 0], 
              [0, 0, 0], 
              [0, 0, 0]])

print(basis_null(A))

# should return something like an identity matrix. The solution is not unique.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
B = np.array([[16, 16, 11],
            [14, 19, 11],
            [11, 12, 19]])

print(basis_null(B))

# should return
# array([[0], [0], [0]])

[[0.]
 [0.]
 [0.]]


In [45]:
C = np.array([[ 0, 18, 16,  9, 6],
                [ 3, 14, 14,  6, 2],
                [14,  3,  4, 18, 8]])


print(basis_null(C))

# should return something like
# array([[-1.51875 , -0.8125], [-3.675,      -3.25], [ 3.571875, 3.28125], [ 1.      , 0], [ 0.      , 1]])
# the solution is not unique

[[-1.51875  -0.8125  ]
 [-3.675    -3.25    ]
 [ 3.571875  3.28125 ]
 [ 1.        0.      ]
 [ 0.        1.      ]]


We will use more test cases when testing your implementation.